import json
import re

def extract_json_from_text(text: str, text_fields: list, number_fields: list = None, confidence_field: str = None) -> dict:
    """
    Extracts structured JSON fields from raw text output generated by LLMs.
    Supports parsing via direct JSON load, code block regex search, candidate bracket substring,
    and a robust key-value regex extraction fallback mechanism.
    """
    if number_fields is None:
        number_fields = []
        
    def clean_data(d):
        if not isinstance(d, dict):
            return {}
        res = {}
        for f in text_fields:
            res[f] = str(d.get(f, ""))
        for f in number_fields:
            try:
                res[f] = float(d.get(f, 0.0))
            except (ValueError, TypeError):
                res[f] = 0.0
        if confidence_field:
            try:
                res[confidence_field] = float(d.get(confidence_field, 0.0))
            except (ValueError, TypeError):
                res[confidence_field] = 0.0
        return res

    # 1. Try to load directly
    try:
        data = json.loads(text.strip())
        if isinstance(data, dict):
            return clean_data(data)
    except json.JSONDecodeError:
        pass

    # 2. Try to find a JSON block using regex
    match = re.search(r"```(?:json)?\s*(\{[\s\S]*?\})\s*```", text)
    if match:
        try:
            data = json.loads(match.group(1).strip())
            if isinstance(data, dict):
                return clean_data(data)
        except json.JSONDecodeError:
            pass

    # 3. Try to find first '{' and last '}'
    start_idx = text.find('{')
    end_idx = text.rfind('}')
    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        json_candidate = text[start_idx:end_idx+1]
        try:
            data = json.loads(json_candidate.strip())
            if isinstance(data, dict):
                return clean_data(data)
        except json.JSONDecodeError:
            pass

    # 4. Fallback parser: Regex extraction of string values
    parsed = {}
    for field in text_fields:
        pattern = rf'"{field}"\s*:\s*"([\s\S]*?)"(?=\s*(?:,|}}))'
        match_field = re.search(pattern, text)
        if match_field:
            val = match_field.group(1)
            val = val.replace('\\"', '"').replace('\\n', '\n')
            parsed[field] = val
        else:
            parsed[field] = ""

    for field in number_fields:
        pattern = rf'"{field}"\s*:\s*(-?\d+(?:\.\d+)?)'
        match_field = re.search(pattern, text)
        if match_field:
            try:
                parsed[field] = float(match_field.group(1))
            except:
                parsed[field] = 0.0
        else:
            parsed[field] = 0.0

    if confidence_field:
        pattern = rf'"{confidence_field}"\s*:\s*(-?\d+(?:\.\d+)?)'
        match_field = re.search(pattern, text)
        if match_field:
            try:
                parsed[confidence_field] = float(match_field.group(1))
            except:
                parsed[confidence_field] = 0.0
        else:
            parsed[confidence_field] = 0.0

    return parsed
